server:
  port: 8090

spring:
  # redis配置
  redis:
    host: 10.181.8.94
    port: 6379
    password: '030514'
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100

# 项目配置
you-chat:
  websocket-port: 9090