server:
  port: 8080

spring:
  # 数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/you_chat
      username: root
      password: '030514'

  # redis配置
  redis:
    host: 10.181.8.94
    port: 6379
    password: '030514'
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100

# mybatis配置
mybatis:
  # mapper xml文件
  mapper-locations: classpath:mapper/*.xml
  # pojo包
  type-aliases-package: com.zjx.youchat.pojo.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
