server:
  port: 8080

spring:
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: '030514'
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
  # 微服务配置
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true

      routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/user/**, /group/**, /contact/**, /contactApply/**, /message/**
        - id: websocket-server
          uri: lb:ws://websocket-server
          predicates:
            - Path=/ws
