server:
  port: 8081

spring:
  # 数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/you_chat_test
      username: root
      password: '030514'

  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: '030514'
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100

  # 微服务配置
  application:
    name: chat-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

# mybatis配置
mybatis:
  # mapper xml文件
  mapper-locations: classpath:mapper/*.xml
  # pojo包
  type-aliases-package: com.zjx.youchat.chat.domain.po
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

# 项目配置
you-chat:
  websocket-port: 9090
  server:
    # 服务端数据存储目录
    data-path: D:\projects\ProjectData\YouChat
  client:
    # 客户端数据存储目录
    data-path: D:\projects\ProjectData\YouChat